pub const CLIENT: &str = "./tf/bin/linux64/client.so";
pub const SERVER: &str = "./tf/bin/linux64/server.so";
pub const ENGINE: &str = "./bin/linux64/engine.so";
pub static mut SDL: &str = "/usr/lib/libSDL2-2.0.so.0";
pub const VGUIMATSURFACE: &str = "./bin/linux64/vguimatsurface.so";
pub const VGUI: &str = "./bin/linux64/vgui2.so";
pub const MATERIAL_SYSTEM: &str = "./bin/linux64/materialsystem.so";
pub const VSTDLIB: &str = "./bin/linux64/libvstdlib.so";
pub const TIER0: &str = "./bin/linux64/libtier0.so";
