use std::ffi::CStr;

use libc::c_void;

use crate::{cfn, netvars::NetvarType, o, sdk::*, vmt_call};

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub enum PropType {
    INT = 0,
    FLOAT,
    VECTOR,
    VECTOR2D,
    STRING,
    ARRAY,
    DATATABLE,
    INT64,
}

#[repr(C)]
#[derive(Debug, Clone)]
pub struct RecvProp {
    pub var_name: *const i8,
    pub recv_type: PropType,
    pub flags: i32,
    pub string_buffer_size: i32,
    pub inside_array: bool,
    pub extra_data: *const c_void,
    pub array_prop: *const RecvProp,
    pub array_length_proxy_fn: cfn!((), ()),
    pub proxy_fn: cfn!((), ()),
    pub data_table_proxy_fn: cfn!((), ()),
    pub data_table: *const RecvTable,
    pub offset: i32,
    pub element_tride: i32,
    pub elements: i32,
    pub parent_array_prop_name: *const char,
}

#[repr(C)]
#[derive(Debug, Clone)]
pub struct RecvTable {
    pub props: *mut RecvProp,
    pub props_count: i32,
    pub decoder: cfn!((), ()),
    pub table_name: *const i8,
    pub initialized: bool,
    pub in_main_list: bool,
}

#[repr(C)]
#[derive(Debug, Clone)]
pub struct UnparsedClientClass {
    _pad1: [i64; 2],
    pub network_name: *const char,
    pub recv_table: &'static RecvTable,
    pub next: &'static UnparsedClientClass,
    pub class_id: ClassId,
}

#[repr(C)]
#[derive(Debug, Clone)]
pub struct ClientClass {
    pub network_name: String,
    pub next: *const UnparsedClientClass,
    pub recv_table: *const RecvTable,
    pub class_id: ClassId,
}
impl ClientClass {
    pub fn get_ingeritance_chain(&self) -> Vec<String> {
        let mut netvars = o!().netvars.get(&self.network_name).unwrap();
        let mut res = vec![self.network_name.clone()];
        loop {
            let Some(netvar) = netvars.get("baseclass") else {break;};
            let NetvarType::OBJECT((name,next_netvars)) = &netvar.netvar_type else {break;};
            res.push(name.clone());
            netvars = next_netvars;
        }
        res
    }
}
impl From<UnparsedClientClass> for ClientClass {
    fn from(value: UnparsedClientClass) -> Self {
        let network_name = if !value.network_name.is_null() {
            unsafe {
                CStr::from_ptr(value.network_name as *const i8)
                    .to_str()
                    .unwrap()
                    .to_owned()
            }
        } else {
            "".to_string()
        };
        ClientClass {
            network_name,
            next: value.next,
            recv_table: value.recv_table,
            class_id: value.class_id,
        }
    }
}

#[repr(C)]
#[derive(Derivative, Clone)]
#[derivative(Debug)]
pub struct VMTNetworkable {
    _pad1: [i64; 2],
    get_client_class: cfn!(&'static UnparsedClientClass, *const Networkable),
    _pad2: [i64; 5],
    pub is_dormant: cfn!(bool, *const Networkable),
    pub get_index: cfn!(isize, *const Networkable),
}

pub type Networkable = WithVmt<VMTNetworkable>;

impl Networkable {
    pub fn get_client_class(&self) -> ClientClass {
        (*vmt_call!(self, get_client_class)).clone().into()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ClassId {
    CTFWearableRazorback = 341,
    CTFWearableDemoShield = 338,
    CTFWearableLevelableItem = 340,
    CTFWearableCampaignItem = 337,
    CTFBaseRocket = 185,
    CTFWeaponBaseMerasmusGrenade = 325,
    CTFWeaponBaseMelee = 324,
    CTFWeaponBaseGun = 323,
    CTFWeaponBaseGrenadeProj = 322,
    CTFWeaponBase = 321,
    CTFWearableRobotArm = 342,
    CTFRobotArm = 287,
    CTFWrench = 344,
    CTFProjectileThrowableBreadMonster = 279,
    CTFProjectileThrowableBrick = 280,
    CTFProjectileThrowableRepel = 281,
    CTFProjectileThrowable = 278,
    CTFThrowable = 319,
    CTFSyringeGun = 315,
    CTFKatana = 225,
    CTFSword = 314,
    CSniperDot = 118,
    CTFSniperRifleClassic = 308,
    CTFSniperRifleDecap = 309,
    CTFSniperRifle = 307,
    CTFChargedSMG = 197,
    CTFSMG = 306,
    CTFSlap = 305,
    CTFShovel = 304,
    CTFShotgunBuildingRescue = 303,
    CTFPEPBrawlerBlaster = 241,
    CTFSodaPopper = 310,
    CTFShotgunRevenge = 301,
    CTFScatterGun = 297,
    CTFShotgunPyro = 300,
    CTFShotgunHWG = 299,
    CTFShotgunSoldier = 302,
    CTFShotgun = 298,
    CTFRocketPack = 296,
    CTFCrossbow = 201,
    CTFRocketLauncherMortar = 295,
    CTFRocketLauncherAirStrike = 293,
    CTFRocketLauncherDirectHit = 294,
    CTFRocketLauncher = 292,
    CTFRevolver = 286,
    CTFDRGPomson = 202,
    CTFRaygun = 284,
    CTFPistolScoutSecondary = 246,
    CTFPistolScoutPrimary = 245,
    CTFPistolScout = 244,
    CTFPistol = 243,
    CTFPipebombLauncher = 242,
    CTFWeaponPDASpy = 332,
    CTFWeaponPDAEngineerDestroy = 331,
    CTFWeaponPDAEngineerBuild = 330,
    CTFWeaponPDAExpansionTeleporter = 334,
    CTFWeaponPDAExpansionDispenser = 333,
    CTFWeaponPDA = 329,
    CTFParticleCannon = 239,
    CTFParachuteSecondary = 238,
    CTFParachutePrimary = 237,
    CTFParachute = 236,
    CTFMinigun = 234,
    CTFMedigunShield = 231,
    CWeaponMedigun = 352,
    CTFProjectileMechanicalArmOrb = 263,
    CTFMechanicalArm = 230,
    CTFLunchBoxDrink = 229,
    CTFLunchBox = 228,
    CLaserDot = 78,
    CTFLaserPointer = 227,
    CTFKnife = 226,
    CTFGasManager = 212,
    CTFProjectileJarGas = 261,
    CTFJarGas = 223,
    CTFProjectileCleaver = 254,
    CTFProjectileJarMilk = 262,
    CTFProjectileJar = 260,
    CTFCleaver = 198,
    CTFJarMilk = 224,
    CTFJar = 222,
    CTFWeaponInvis = 328,
    CTFCannon = 196,
    CTFGrenadeLauncher = 216,
    CTFGrenadePipebombProjectile = 217,
    CTFGrapplingHook = 215,
    CTFFlareGunRevenge = 210,
    CTFFlareGun = 209,
    CTFFlameRocket = 207,
    CTFFlameThrower = 208,
    CTFFists = 205,
    CTFFireAxe = 204,
    CTFWeaponFlameBall = 327,
    CTFCompoundBow = 200,
    CTFClub = 199,
    CTFBuffItem = 195,
    CTFStickBomb = 312,
    CTFBreakableSign = 194,
    CTFBottle = 192,
    CTFBreakableMelee = 193,
    CTFBonesaw = 190,
    CTFBallOrnament = 182,
    CTFStunBall = 313,
    CTFBatGiftwrap = 188,
    CTFBatWood = 189,
    CTFBatFish = 187,
    CTFBat = 186,
    CTFProjectileEnergyRing = 256,
    CTFDroppedWeapon = 203, /* !!! */
    CTFWeaponSapper = 335,
    CTFWeaponBuilder = 326,
    CTFProjectileRocket = 264,
    CTFProjectileFlare = 257,
    CTFProjectileEnergyBall = 255,
    CTFProjectileGrapplingHook = 258,
    CTFProjectileHealingBolt = 259,
    CTFProjectileArrow = 252,
    CMannVsMachineStats = 80,
    CTFTankBoss = 316,
    CTFBaseBoss = 183,
    NextBotCombatCharacter = 357,
    CTFProjectileSpellKartBats = 268,
    CTFProjectileSpellKartOrb = 269,
    CTFHellZap = 220,
    CTFProjectileSpellLightningOrb = 270,
    CTFProjectileSpellTransposeTeleport = 277,
    CTFProjectileSpellMeteorShower = 271,
    CTFProjectileSpellSpawnBoss = 274,
    CTFProjectileSpellMirv = 272,
    CTFProjectileSpellPumpkin = 273,
    CTFProjectileSpellSpawnHorde = 275,
    CTFProjectileSpellSpawnZombie = 276,
    CTFProjectileSpellBats = 266,
    CTFProjectileSpellFireball = 267,
    CTFSpellBook = 311,
    CHightowerTeleportVortex = 74,
    CTeleportVortex = 160,
    CZombie = 354,
    CMerasmusDancer = 83,
    CMerasmus = 82,
    CHeadlessHatman = 73,
    CEyeballBoss = 48,
    CTFBotHintEngineerNest = 191,
    CPasstimeGun = 94,
    CTFViewModel = 320,
    CRobotDispenser = 112,
    CTFRobotDestructionRobot = 288,
    CTFReviveMarker = 285,
    CTFPumpkinBomb = 282,
    CTFProjectileBallOfFire = 253,
    CTFBaseProjectile = 184,
    CTFPointManager = 250,
    CBaseObjectUpgrade = 11,
    CTFRobotDestructionLogic = 291,
    CTFRobotDestructionRobotGroup = 289,
    CTFRobotDestructionRobotSpawn = 290,
    CTFPlayerDestructionLogic = 248,
    CPlayerDestructionDispenser = 101,
    CTFMinigameLogic = 233,
    CTFHalloweenMinigameFallingPlatforms = 219,
    CTFHalloweenMinigame = 218,
    CTFMiniGame = 232,
    CTFPowerupBottle = 251,
    CTFItem = 221,
    CHalloweenSoulPack = 71,
    CTFGenericBomb = 213,
    CBonusRoundLogic = 23,
    CTFGameRulesProxy = 211,
    CTETFParticleEffect = 179,
    CTETFExplosion = 178,
    CTETFBlood = 177,
    CTFFlameManager = 206,
    CHalloweenGiftPickup = 69,
    CBonusDuckPickup = 21,
    CHalloweenPickup = 70,
    CCaptureFlagReturnIcon = 27,
    CCaptureFlag = 26,
    CBonusPack = 22,
    CTFTeam = 318,
    CTFTauntProp = 317,
    CTFPlayerResource = 249,
    CTFPlayer = 247, /* !!! */
    CTFRagdoll = 283,
    CTEPlayerAnimEvent = 165,
    CTFPasstimeLogic = 240,
    CPasstimeBall = 93,
    CTFObjectiveResource = 235,
    CTFGlow = 214,
    CTEFireBullets = 152,
    CTFAmmoPack = 181,      /* !!! */
    CObjectTeleporter = 89, /* !!! */
    CObjectSentrygun = 88,  /* !!! */
    CTFProjectileSentryRocket = 265,
    CObjectSapper = 87,
    CObjectCartDispenser = 85,
    CObjectDispenser = 86, /* !!! */
    CMonsterResource = 84,
    CFuncRespawnRoomVisualizer = 64,
    CFuncRespawnRoom = 63,
    CFuncPasstimeGoal = 61,
    CFuncForceField = 57,
    CCaptureZone = 28,
    CCurrencyPack = 31, /* !!! */
    CBaseObject = 10,
    CTestTraceline = 176,
    CTEWorldDecal = 180,
    CTESpriteSpray = 174,
    CTESprite = 173,
    CTESparks = 172,
    CTESmoke = 171,
    CTEShowLine = 169,
    CTEProjectedDecal = 167,
    CTEPlayerDecal = 166,
    CTEPhysicsProp = 164,
    CTEParticleSystem = 163,
    CTEMuzzleFlash = 162,
    CTELargeFunnel = 159,
    CTEKillPlayerAttachments = 158,
    CTEImpact = 157,
    CTEGlowSprite = 156,
    CTEShatterSurface = 168,
    CTEFootprintDecal = 154,
    CTEFizz = 153,
    CTEExplosion = 151,
    CTEEnergySplash = 150,
    CTEEffectDispatch = 149,
    CTEDynamicLight = 148,
    CTEDecal = 146,
    CTEClientProjectile = 145,
    CTEBubbleTrail = 144,
    CTEBubbles = 143,
    CTEBSPDecal = 142,
    CTEBreakModel = 141,
    CTEBloodStream = 140,
    CTEBloodSprite = 139,
    CTEBeamSpline = 138,
    CTEBeamRingPoint = 137,
    CTEBeamRing = 136,
    CTEBeamPoints = 135,
    CTEBeamLaser = 134,
    CTEBeamFollow = 133,
    CTEBeamEnts = 132,
    CTEBeamEntPoint = 131,
    CTEBaseBeam = 130,
    CTEArmorRicochet = 129,
    CTEMetalSparks = 161,
    CSteamJet = 123,
    CSmokeStack = 117,
    DustTrail = 355,
    CFireTrail = 50,
    SporeTrail = 362,
    SporeExplosion = 361,
    RocketTrail = 359,
    SmokeTrail = 360,
    CPropVehicleDriveable = 108,
    ParticleSmokeGrenade = 358,
    CParticleFire = 90,
    MovieExplosion = 356,
    CTEGaussExplosion = 155,
    CEnvQuadraticBeam = 43,
    CEmbers = 36,
    CEnvWind = 47,
    CPrecipitation = 107,
    CBaseTempEntity = 17,
    CWeaponIFMSteadyCam = 351,
    CWeaponIFMBaseCamera = 350,
    CWeaponIFMBase = 349,
    CTFWearableVM = 343,
    CTFWearable = 336,
    CTFWearableItem = 339,
    CEconWearable = 35,
    CBaseAttributableItem = 3,
    CEconEntity = 34,
    CHandleTest = 72,
    CTeamplayRoundBasedRulesProxy = 126,
    CTeamRoundTimer = 127,
    CSpriteTrail = 122,
    CSpriteOriented = 121,
    CSprite = 120,
    CRagdollPropAttached = 111,
    CRagdollProp = 110,
    CPoseController = 106,
    CGameRulesProxy = 68,
    CInfoLadderDismount = 75,
    CFuncLadder = 58,
    CEnvDetailController = 40,
    CWorld = 353,
    CWaterLODControl = 348,
    CWaterBullet = 347,
    CVoteController = 346,
    CVGuiScreen = 345,
    CTestProxyToggleNetworkable = 175,
    CTesla = 170,
    CTeamTrainWatcher = 128,
    CBaseTeamObjectiveResource = 16,
    CTeam = 125,
    CSun = 124,
    CParticlePerformanceMonitor = 91,
    CSpotlightEnd = 119,
    CSlideshowDisplay = 116,
    CShadowControl = 115,
    CSceneEntity = 114,
    CRopeKeyframe = 113,
    CRagdollManager = 109,
    CPhysicsPropMultiplayer = 98,
    CPhysBoxMultiplayer = 96,
    CBasePropDoor = 15,
    CDynamicProp = 33,
    CPointWorldText = 105,
    CPointCommentaryNode = 104,
    CPointCamera = 103,
    CPlayerResource = 102,
    CPlasma = 100,
    CPhysMagnet = 99,
    CPhysicsProp = 97,
    CPhysBox = 95,
    CParticleSystem = 92,
    CMaterialModifyControl = 81,
    CLightGlow = 79,
    CInfoOverlayAccessor = 77,
    CFuncTrackTrain = 67,
    CFuncSmokeVolume = 66,
    CFuncRotating = 65,
    CFuncReflectiveGlass = 62,
    CFuncOccluder = 60,
    CFuncMonitor = 59,
    CFuncLOD = 54,
    CTEDust = 147,
    CFuncDust = 53,
    CFuncConveyor = 56,
    CBreakableSurface = 25,
    CFuncAreaPortalWindow = 55,
    CFish = 51,
    CEntityFlame = 38,
    CFireSmoke = 49,
    CEnvTonemapController = 46,
    CEnvScreenEffect = 44,
    CEnvScreenOverlay = 45,
    CEnvProjectedTexture = 42,
    CEnvParticleScript = 41,
    CFogController = 52,
    CEntityParticleTrail = 39,
    CEntityDissolve = 37,
    CDynamicLight = 32,
    CColorCorrectionVolume = 30,
    CColorCorrection = 29,
    CBreakableProp = 24,
    CBasePlayer = 13,
    CBaseFlex = 8,
    CBaseEntity = 7,
    CBaseDoor = 6,
    CBaseCombatCharacter = 4,
    CBaseAnimatingOverlay = 2,
    CBoneFollower = 20,
    CBaseAnimating = 1, /* !!! */
    CInfoLightingRelative = 76,
    CBeam = 19,
    CBaseViewModel = 18,
    CBaseProjectile = 14,
    CBaseParticleEntity = 12,
    CBaseGrenade = 9,
    CBaseCombatWeapon = 5,
}
