use derivative::Derivative;

#[derive(Debug, Hash, PartialEq, PartialOrd, Eq, Clone)]
#[repr(i32)]
pub enum WeaponId {
    None = 0,
    Bat,
    BatWood,
    Bottle,
    Fireaxe,
    Club,
    Crowbar,
    Knife,
    Fists,
    Shovel,
    Wrench,
    Bonesaw,
    ShotgunPrimary,
    ShotgunSoldier,
    ShotgunHwg,
    ShotgunPyro,
    Scattergun,
    Sniperrifle,
    Minigun,
    Smg,
    SyringegunMedic,
    Tranq,
    Rocketlauncher,
    Grenadelauncher,
    Pipebomblauncher,
    Flamethrower,
    GrenadeNormal,
    GrenadeConcussion,
    GrenadeNail,
    GrenadeMirv,
    GrenadeMirvDemoman,
    GrenadeNapalm,
    GrenadeGas,
    GrenadeEmp,
    GrenadeCaltrop,
    GrenadePipebomb,
    GrenadeSmokeBomb,
    GrenadeHeal,
    GrenadeStunball,
    GrenadeJar,
    GrenadeJarMilk,
    Pistol,
    PistolScout,
    Revolver,
    Nailgun,
    Pda,
    PdaEngineerBuild,
    PdaEngineerDestroy,
    PdaSpy,
    Builder,
    Medigun,
    GrenadeMirvbomb,
    FlamethrowerRocket,
    GrenadeDemoman,
    SentryBullet,
    SentryRocket,
    Dispenser,
    Invis,
    Flaregun,
    Lunchbox,
    Jar,
    CompoundBow,
    BuffItem,
    PumpkinBomb,
    Sword,
    RocketlauncherDirecthit,
    Lifeline,
    LaserPointer,
    DispenserGun,
    SentryRevenge,
    JarMilk,
    HandgunScoutPrimary,
    BatFish,
    Crossbow,
    Stickbomb,
    HandgunScoutSecondary,
    SodaPopper,
    SniperrifleDecap,
    Raygun,
    ParticleCannon,
    MechanicalArm,
    DrgPomson,
    BatGiftwrap,
    GrenadeOrnamentBall,
    FlaregunRevenge,
    PepBrawlerBlaster,
    Cleaver,
    GrenadeCleaver,
    StickyBallLauncher,
    GrenadeStickyBall,
    ShotgunBuildingRescue,
    Cannon,
    Throwable,
    GrenadeThrowable,
    PdaSpyBuild,
    GrenadeWaterballoon,
    HarvesterSaw,
    Spellbook,
    SpellbookProjectile,
    SniperrifleClassic,
    Parachute,
    Grapplinghook,
    PasstimeGun,
    ChargedSmg,
	BreakableSign,
	Rocketpack,
	Slap,
	JarGas,
	GrenadeJarGas,
	FlameBall
}

#[derive(Derivative, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum ItemDefinitionInex {
    ScoutMScattergun = 13,
    ScoutMScattergunR = 200,
    ScoutMForceANature = 45,
    ScoutMTheShortstop = 220,
    ScoutMTheSodaPopper = 448,
    ScoutMFestiveScattergun = 669,
    ScoutMBabyFacesBlaster = 772,
    ScoutMSilverBotkillerScattergunMkI = 799,
    ScoutMGoldBotkillerScattergunMkI = 808,
    ScoutMRustBotkillerScattergunMkI = 888,
    ScoutMBloodBotkillerScattergunMkI = 897,
    ScoutMCarbonadoBotkillerScattergunMkI = 906,
    ScoutMDiamondBotkillerScattergunMkI = 915,
    ScoutMSilverBotkillerScattergunMkII = 964,
    ScoutMGoldBotkillerScattergunMkII = 973,
    ScoutMFestiveForceANature = 1078,
    ScoutMTheBackScatter = 1103,
    ScoutMNightTerror = 15002,
    ScoutMTartanTorpedo = 15015,
    ScoutMCountryCrusher = 15021,
    ScoutMBackcountryBlaster = 15029,
    ScoutMSpruceDeuce = 15036,
    ScoutMCurrentEvent = 15053,
    ScoutMMacabreWeb = 15065,
    ScoutMNutcracker = 15069,
    ScoutMBlueMew = 15106,
    ScoutMFlowerPower = 15107,
    ScoutMShottoHell = 15108,
    ScoutMCoffinNail = 15131,
    ScoutMKillerBee = 15151,
    ScoutMCorsair = 15157,
    ScoutSScoutsPistol = 23,
    ScoutSBonkAtomicPunch = 46,
    ScoutSCritaCola = 163,
    ScoutSMadMilk = 222,
    ScoutSTheWinger = 449,
    ScoutSPrettyBoysPocketPistol = 773,
    ScoutSTheFlyingGuillotine = 812,
    ScoutSTheFlyingGuillotineG = 833,
    ScoutSMutatedMilk = 1121,
    ScoutSFestiveBonk = 1145,
    ScoutTBat = 0,
    ScoutTBatR = 190,
    ScoutTTheSandman = 44,
    ScoutTTheHolyMackerel = 221,
    ScoutTTheCandyCane = 317,
    ScoutTTheBostonBasher = 325,
    ScoutTSunonaStick = 349,
    ScoutTTheFanOWar = 355,
    ScoutTTheAtomizer = 450,
    ScoutTThreeRuneBlade = 452,
    ScoutTUnarmedCombat = 572,
    ScoutTTheWrapAssassin = 648,
    ScoutTFestiveBat = 660,
    ScoutTFestiveHolyMackerel = 999,
    ScoutTBatsaber = 30667,
    SoldierMRocketLauncher = 18,
    SoldierMRocketLauncherR = 205,
    SoldierMTheDirectHit = 127,
    SoldierMTheBlackBox = 228,
    SoldierMRocketJumper = 237,
    SoldierMTheLibertyLauncher = 414,
    SoldierMTheCowMangler5000 = 441,
    SoldierMTheOriginal = 513,
    SoldierMFestiveRocketLauncher = 658,
    SoldierMTheBeggarsBazooka = 730,
    SoldierMSilverBotkillerRocketLauncherMkI = 800,
    SoldierMGoldBotkillerRocketLauncherMkI = 809,
    SoldierMRustBotkillerRocketLauncherMkI = 889,
    SoldierMBloodBotkillerRocketLauncherMkI = 898,
    SoldierMCarbonadoBotkillerRocketLauncherMkI = 907,
    SoldierMDiamondBotkillerRocketLauncherMkI = 916,
    SoldierMSilverBotkillerRocketLauncherMkII = 965,
    SoldierMGoldBotkillerRocketLauncherMkII = 974,
    SoldierMFestiveBlackBox = 1085,
    SoldierMTheAirStrike = 1104,
    SoldierMWoodlandWarrior = 15006,
    SoldierMSandCannon = 15014,
    SoldierMAmericanPastoral = 15028,
    SoldierMSmalltownBringdown = 15043,
    SoldierMShellShocker = 15052,
    SoldierMAquaMarine = 15057,
    SoldierMAutumn = 15081,
    SoldierMBlueMew = 15104,
    SoldierMBrainCandy = 15105,
    SoldierMHighRollers = 15130,
    SoldierMWarhawk = 15150,
    SoldierSSoldiersShotgun = 10,
    SoldierSTheBuffBanner = 129,
    SoldierSGunboats = 133,
    SoldierSTheBattalionsBackup = 226,
    SoldierSTheConcheror = 354,
    SoldierSTheRighteousBison = 442,
    SoldierSTheMantreads = 444,
    SoldierSFestiveBuffBanner = 1001,
    SoldierTShovel = 6,
    SoldierTShovelR = 196,
    SoldierTTheEqualizer = 128,
    SoldierTTheMarketGardener = 416,
    SoldierTTheDisciplinaryAction = 447,
    SoldierTTheEscapePlan = 775,
    PyroMFlameThrower = 21,
    PyroMFlameThrowerR = 208,
    PyroMTheBackburner = 40,
    PyroMTheDegreaser = 215,
    PyroMThePhlogistinator = 594,
    PyroMFestiveFlameThrower = 659,
    PyroMTheRainblower = 741,
    PyroMSilverBotkillerFlameThrowerMkI = 798,
    PyroMGoldBotkillerFlameThrowerMkI = 807,
    PyroMRustBotkillerFlameThrowerMkI = 887,
    PyroMBloodBotkillerFlameThrowerMkI = 896,
    PyroMCarbonadoBotkillerFlameThrowerMkI = 905,
    PyroMDiamondBotkillerFlameThrowerMkI = 914,
    PyroMSilverBotkillerFlameThrowerMkII = 963,
    PyroMGoldBotkillerFlameThrowerMkII = 972,
    PyroMFestiveBackburner = 1146,
    PyroMDragonsFury = 1178,
    PyroMForestFire = 15005,
    PyroMBarnBurner = 15017,
    PyroMBovineBlazemaker = 15030,
    PyroMEarthSkyandFire = 15034,
    PyroMFlashFryer = 15049,
    PyroMTurbineTorcher = 15054,
    PyroMAutumn = 15066,
    PyroMPumpkinPatch = 15067,
    PyroMNutcracker = 15068,
    PyroMBalloonicorn = 15089,
    PyroMRainbow = 15090,
    PyroMCoffinNail = 15115,
    PyroMWarhawk = 15141,
    PyroMNostromoNapalmer = 30474,
    PyroSPyrosShotgun = 12,
    PyroSTheFlareGun = 39,
    PyroSTheDetonator = 351,
    PyroSTheReserveShooter = 415,
    PyroSTheManmelter = 595,
    PyroSTheScorchShot = 740,
    PyroSFestiveFlareGun = 1081,
    PyroSThermalThruster = 1179,
    PyroSGasPasser = 1180,
    PyroTFireAxe = 2,
    PyroTFireAxeR = 192,
    PyroTTheAxtinguisher = 38,
    PyroTHomewrecker = 153,
    PyroTThePowerjack = 214,
    PyroTTheBackScratcher = 326,
    PyroTSharpenedVolcanoFragment = 348,
    PyroTThePostalPummeler = 457,
    PyroTTheMaul = 466,
    PyroTTheThirdDegree = 593,
    PyroTTheLollichop = 739,
    PyroTNeonAnnihilator = 813,
    PyroTNeonAnnihilatorG = 834,
    PyroTTheFestiveAxtinguisher = 1000,
    PyroTHotHand = 1181,
    DemomanMGrenadeLauncher = 19,
    DemomanMGrenadeLauncherR = 206,
    DemomanMTheLochnLoad = 308,
    DemomanMAliBabasWeeBooties = 405,
    DemomanMTheBootlegger = 608,
    DemomanMTheLooseCannon = 996,
    DemomanMFestiveGrenadeLauncher = 1007,
    DemomanMTheBASEJumper = 1101,
    DemomanMTheIronBomber = 1151,
    DemomanMAutumn = 15077,
    DemomanMMacabreWeb = 15079,
    DemomanMRainbow = 15091,
    DemomanMSweetDreams = 15092,
    DemomanMCoffinNail = 15116,
    DemomanMTopShelf = 15117,
    DemomanMWarhawk = 15142,
    DemomanMButcherBird = 15158,
    DemomanSStickybombLauncher = 20,
    DemomanSStickybombLauncherR = 207,
    DemomanSTheScottishResistance = 130,
    DemomanSTheCharginTarge = 131,
    DemomanSStickyJumper = 265,
    DemomanSTheSplendidScreen = 406,
    DemomanSFestiveStickybombLauncher = 661,
    DemomanSSilverBotkillerStickybombLauncherMkI = 797,
    DemomanSGoldBotkillerStickybombLauncherMkI = 806,
    DemomanSRustBotkillerStickybombLauncherMkI = 886,
    DemomanSBloodBotkillerStickybombLauncherMkI = 895,
    DemomanSCarbonadoBotkillerStickybombLauncherMkI = 904,
    DemomanSDiamondBotkillerStickybombLauncherMkI = 913,
    DemomanSSilverBotkillerStickybombLauncherMkII = 962,
    DemomanSGoldBotkillerStickybombLauncherMkII = 971,
    DemomanSTheTideTurner = 1099,
    DemomanSFestiveTarge = 1144,
    DemomanSTheQuickiebombLauncher = 1150,
    DemomanSSuddenFlurry = 15009,
    DemomanSCarpetBomber = 15012,
    DemomanSBlastedBombardier = 15024,
    DemomanSRooftopWrangler = 15038,
    DemomanSLiquidAsset = 15045,
    DemomanSPinkElephant = 15048,
    DemomanSAutumn = 15082,
    DemomanSPumpkinPatch = 15083,
    DemomanSMacabreWeb = 15084,
    DemomanSSweetDreams = 15113,
    DemomanSCoffinNail = 15137,
    DemomanSDressedtoKill = 15138,
    DemomanSBlitzkrieg = 15155,
    DemomanTBottle = 1,
    DemomanTBottleR = 191,
    DemomanTTheEyelander = 132,
    DemomanTThePainTrain = 154,
    DemomanTTheScotsmansSkullcutter = 172,
    DemomanTHorselessHeadlessHorsemannsHeadtaker = 266,
    DemomanTUllapoolCaber = 307,
    DemomanTTheClaidheamhMor = 327,
    DemomanTTheHalfZatoichi = 357,
    DemomanTThePersianPersuader = 404,
    DemomanTNessiesNineIron = 482,
    DemomanTTheScottishHandshake = 609,
    DemomanTFestiveEyelander = 1082,
    DemomanTTheNecroSmasher = 1123,
    DemomanTTheCrossingGuard = 1127,
    DemomanTPrinnyMachete = 30758,
    HeavyMMinigun = 15,
    HeavyMMinigunR = 202,
    HeavyMNatascha = 41,
    HeavyMIronCurtain = 298,
    HeavyMTheBrassBeast = 312,
    HeavyMTomislav = 424,
    HeavyMFestiveMinigun = 654,
    HeavyMSilverBotkillerMinigunMkI = 793,
    HeavyMGoldBotkillerMinigunMkI = 802,
    HeavyMTheHuoLongHeater = 811,
    HeavyMTheHuoLongHeaterG = 832,
    HeavyMDeflectorMvm = 850,
    HeavyMRustBotkillerMinigunMkI = 882,
    HeavyMBloodBotkillerMinigunMkI = 891,
    HeavyMCarbonadoBotkillerMinigunMkI = 900,
    HeavyMDiamondBotkillerMinigunMkI = 909,
    HeavyMSilverBotkillerMinigunMkII = 958,
    HeavyMGoldBotkillerMinigunMkII = 967,
    HeavyMKingoftheJungle = 15004,
    HeavyMIronWood = 15020,
    HeavyMAntiqueAnnihilator = 15026,
    HeavyMWarRoom = 15031,
    HeavyMCitizenPain = 15040,
    HeavyMBrickHouse = 15055,
    HeavyMMacabreWeb = 15086,
    HeavyMPumpkinPatch = 15087,
    HeavyMNutcracker = 15088,
    HeavyMBrainCandy = 15098,
    HeavyMMisterCuddles = 15099,
    HeavyMCoffinNail = 15123,
    HeavyMDressedtoKill = 15124,
    HeavyMTopShelf = 15125,
    HeavyMButcherBird = 15147,
    HeavySHeavysShotgun = 11,
    HeavySShotgunR = 199,
    HeavySSandvich = 42,
    HeavySTheDalokohsBar = 159,
    HeavySTheBuffaloSteakSandvich = 311,
    HeavySTheFamilyBusiness = 425,
    HeavySFishcake = 433,
    HeavySRoboSandvich = 863,
    HeavySFestiveSandvich = 1002,
    HeavySFestiveShotgun = 1141,
    HeavySPanicAttack = 1153,
    HeavySSecondBanana = 1190,
    HeavySBackwoodsBoomstick = 15003,
    HeavySRusticRuiner = 15016,
    HeavySCivicDuty = 15044,
    HeavySLightningRod = 15047,
    HeavySAutumn = 15085,
    HeavySFlowerPower = 15109,
    HeavySCoffinNail = 15132,
    HeavySDressedtoKill = 15133,
    HeavySRedBear = 15152,
    HeavyTFists = 5,
    HeavyTFistsR = 195,
    HeavyTTheKillingGlovesofBoxing = 43,
    HeavyTGlovesofRunningUrgently = 239,
    HeavyTWarriorsSpirit = 310,
    HeavyTFistsofSteel = 331,
    HeavyTTheEvictionNotice = 426,
    HeavyTTheConscientiousObjector = 474,
    HeavyTApocoFists = 587,
    HeavyTTheHolidayPunch = 656,
    HeavyTTheFreedomStaff = 880,
    HeavyTTheBatOuttaHell = 939,
    HeavyTTheMemoryMaker = 954,
    HeavyTTheHamShank = 1013,
    HeavyTFestiveGlovesofRunningUrgently = 1084,
    HeavyTTheBreadBite = 1100,
    HeavyTGlovesofRunningUrgentlyMvM = 1184,
    EngiMEngineersShotgun = 9,
    EngiMTheFrontierJustice = 141,
    EngiMTheWidowmaker = 527,
    EngiMThePomson6000 = 588,
    EngiMTheRescueRanger = 997,
    EngiMFestiveFrontierJustice = 1004,
    EngiSEngineersPistol = 22,
    EngiSPistolR = 209,
    EngiSTheWrangler = 140,
    EngiSVintageLugermorph = 160,
    EngiSLugermorph = 294,
    EngiSTheShortCircuit = 528,
    EngiSFestiveWrangler = 1086,
    EngiSRedRockRoscoe = 15013,
    EngiSHomemadeHeater = 15018,
    EngiSHickoryHolepuncher = 15035,
    EngiSLocalHero = 15041,
    EngiSBlackDahlia = 15046,
    EngiSSandstoneSpecial = 15056,
    EngiSMacabreWeb = 15060,
    EngiSNutcracker = 15061,
    EngiSBlueMew = 15100,
    EngiSBrainCandy = 15101,
    EngiSShottoHell = 15102,
    EngiSDressedToKill = 15126,
    EngiSBlitzkrieg = 15148,
    EngiSTheCAPPER = 30666,
    EngiSTheGigarCounter = 30668,
    EngiTWrench = 7,
    EngiTWrenchR = 197,
    EngiTTheGunslinger = 142,
    EngiTTheSouthernHospitality = 155,
    EngiTGoldenWrench = 169,
    EngiTTheJag = 329,
    EngiTTheEurekaEffect = 589,
    EngiTFestiveWrench = 662,
    EngiTSilverBotkillerWrenchMkI = 795,
    EngiTGoldBotkillerWrenchMkI = 804,
    EngiTRustBotkillerWrenchMkI = 884,
    EngiTBloodBotkillerWrenchMkI = 893,
    EngiTCarbonadoBotkillerWrenchMkI = 902,
    EngiTDiamondBotkillerWrenchMkI = 911,
    EngiTSilverBotkillerWrenchMkII = 960,
    EngiTGoldBotkillerWrenchMkII = 969,
    EngiTNutcracker = 15073,
    EngiTAutumn = 15074,
    EngiTBoneyard = 15075,
    EngiTDressedtoKill = 15139,
    EngiTTopShelf = 15140,
    EngiTTorquedtoHell = 15114,
    EngiTAirwolf = 15156,
    EngiPConstructionPDA = 25,
    EngiPConstructionPDAR = 737,
    EngiPDestructionPDA = 26,
    EngiPPDA = 28,
    MedicMSyringeGun = 17,
    MedicMSyringeGunR = 204,
    MedicMTheBlutsauger = 36,
    MedicMCrusadersCrossbow = 305,
    MedicMTheOverdose = 412,
    MedicMFestiveCrusadersCrossbow = 1079,
    MedicSMediGun = 29,
    MedicSMediGunR = 211,
    MedicSTheKritzkrieg = 35,
    MedicSTheQuickFix = 411,
    MedicSFestiveMediGun = 663,
    MedicSSilverBotkillerMediGunMkI = 796,
    MedicSGoldBotkillerMediGunMkI = 805,
    MedicSRustBotkillerMediGunMkI = 885,
    MedicSBloodBotkillerMediGunMkI = 894,
    MedicSCarbonadoBotkillerMediGunMkI = 903,
    MedicSDiamondBotkillerMediGunMkI = 912,
    MedicSSilverBotkillerMediGunMkII = 961,
    MedicSGoldBotkillerMediGunMkII = 970,
    MedicSTheVaccinator = 998,
    MedicSMaskedMender = 15008,
    MedicSWrappedReviver = 15010,
    MedicSReclaimedReanimator = 15025,
    MedicSCivilServant = 15039,
    MedicSSparkofLife = 15050,
    MedicSWildwood = 15078,
    MedicSFlowerPower = 15097,
    MedicSDressedToKill = 15121,
    MedicSHighRollers = 15122,
    MedicSBlitzkrieg = 15145,
    MedicSCorsair = 15146,
    MedicTBonesaw = 8,
    MedicTBonesawR = 198,
    MedicTTheUbersaw = 37,
    MedicTTheVitaSaw = 173,
    MedicTAmputator = 304,
    MedicTTheSolemnVow = 413,
    MedicTFestiveBonesaw = 1143,
    SniperMSniperRifle = 14,
    SniperMSniperRifleR = 201,
    SniperMTheHuntsman = 56,
    SniperMTheSydneySleeper = 230,
    SniperMTheBazaarBargain = 402,
    SniperMTheMachina = 526,
    SniperMFestiveSniperRifle = 664,
    SniperMTheHitmansHeatmaker = 752,
    SniperMSilverBotkillerSniperRifleMkI = 792,
    SniperMGoldBotkillerSniperRifleMkI = 801,
    SniperMTheAWPerHand = 851,
    SniperMRustBotkillerSniperRifleMkI = 881,
    SniperMBloodBotkillerSniperRifleMkI = 890,
    SniperMCarbonadoBotkillerSniperRifleMkI = 899,
    SniperMDiamondBotkillerSniperRifleMkI = 908,
    SniperMSilverBotkillerSniperRifleMkII = 957,
    SniperMGoldBotkillerSniperRifleMkII = 966,
    SniperMFestiveHuntsman = 1005,
    SniperMTheFortifiedCompound = 1092,
    SniperMTheClassic = 1098,
    SniperMNightOwl = 15000,
    SniperMPurpleRange = 15007,
    SniperMLumberFromDownUnder = 15019,
    SniperMShotintheDark = 15023,
    SniperMBogtrotter = 15033,
    SniperMThunderbolt = 15059,
    SniperMPumpkinPatch = 15070,
    SniperMBoneyard = 15071,
    SniperMWildwood = 15072,
    SniperMBalloonicorn = 15111,
    SniperMRainbow = 15112,
    SniperMCoffinNail = 15135,
    SniperMDressedtoKill = 15136,
    SniperMAirwolf = 15154,
    SniperMShootingStar = 30665,
    SniperSSMG = 16,
    SniperSSMGR = 203,
    SniperSTheRazorback = 57,
    SniperSJarate = 58,
    SniperSDarwinsDangerShield = 231,
    SniperSCozyCamper = 642,
    SniperSTheCleanersCarbine = 751,
    SniperSFestiveJarate = 1083,
    SniperSTheSelfAwareBeautyMark = 1105,
    SniperSFestiveSMG = 1149,
    SniperSWoodsyWidowmaker = 15001,
    SniperSPlaidPotshotter = 15022,
    SniperSTreadplateTormenter = 15032,
    SniperSTeamSprayer = 15037,
    SniperSLowProfile = 15058,
    SniperSWildwood = 15076,
    SniperSBlueMew = 15110,
    SniperSHighRollers = 15134,
    SniperSBlitzkrieg = 15153,
    SniperTKukri = 3,
    SniperTKukriR = 193,
    SniperTTheTribalmansShiv = 171,
    SniperTTheBushwacka = 232,
    SniperTTheShahanshah = 401,
    SpyMRevolver = 24,
    SpyMRevolverR = 210,
    SpyMTheAmbassador = 61,
    SpyMBigKill = 161,
    SpyMLEtranger = 224,
    SpyMTheEnforcer = 460,
    SpyMTheDiamondback = 525,
    SpyMFestiveAmbassador = 1006,
    SpyMFestiveRevolver = 1142,
    SpyMPsychedelicSlugger = 15011,
    SpyMOldCountry = 15027,
    SpyMMayor = 15042,
    SpyMDeadReckoner = 15051,
    SpyMBoneyard = 15062,
    SpyMWildwood = 15063,
    SpyMMacabreWeb = 15064,
    SpyMFlowerPower = 15103,
    SpyMTopShelf = 15128,
    SpyMCoffinNail = 15129,
    SpyMBlitzkrieg = 15149,
    SpySSapper = 735,
    SpySSapperR = 736,
    SpySTheRedTapeRecorder = 810,
    SpySTheRedTapeRecorderG = 831,
    SpySTheApSapG = 933,
    SpySFestiveSapper = 1080,
    SpySTheSnackAttack = 1102,
    SpyTKnife = 4,
    SpyTKnifeR = 194,
    SpyTYourEternalReward = 225,
    SpyTConniversKunai = 356,
    SpyTTheBigEarner = 461,
    SpyTTheWangaPrick = 574,
    SpyTTheSharpDresser = 638,
    SpyTTheSpycicle = 649,
    SpyTFestiveKnife = 665,
    SpyTTheBlackRose = 727,
    SpyTSilverBotkillerKnifeMkI = 794,
    SpyTGoldBotkillerKnifeMkI = 803,
    SpyTRustBotkillerKnifeMkI = 883,
    SpyTBloodBotkillerKnifeMkI = 892,
    SpyTCarbonadoBotkillerKnifeMkI = 901,
    SpyTDiamondBotkillerKnifeMkI = 910,
    SpyTSilverBotkillerKnifeMkII = 959,
    SpyTGoldBotkillerKnifeMkII = 968,
    SpyDDisguiseKitPDA = 27,
    SpyWInvisWatch = 30,
    SpyWInvisWatchR = 212,
    SpyWTheDeadRinger = 59,
    SpyWTheCloakandDagger = 60,
    SpyWEnthusiastsTimepiece = 297,
    SpyWTheQuackenbirdt = 947,
    MiscTFryingPan = 264,
    MiscTGoldFryingPan = 1071,
    MiscTSaxxy = 423,
}
